#!/bin/bash

echo "Installing general dependencies..."
sudo apt-get update
sudo apt-get upgrade
sudo apt install -y zsh tree-sitter-cli curl ripgrep fzf gcc npm nodejs fd-find
echo "General dependencies installed"

# Install Neovim
if ! type nvim >dev/null; then
  echo "Installing nvim..."
  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.tar.gz
  sudo rm -rf /opt/nvim-linux-x86_64
  sudo tar -C /opt -xzf nvim-linux-x86_64.tar.gz
  rm nvim-linux-x86_64.tar.gz
  echo "nvim installed!"
fi

# Install Lazygit
if ! type lazygit; then
  echo "Installing lazygit..."
  LAZYGIT_VERSION=$(curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest" | \grep -Po '"tag_name": *"v\K[^"]*')
  curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/download/v${LAZYGIT_VERSION}/lazygit_${LAZYGIT_VERSION}_Linux_x86_64.tar.gz"
  tar xf lazygit.tar.gz lazygit
  sudo install lazygit -D -t /usr/local/bin/
  rm lazygit.tar.gz
  echo "lazygit installed!"
fi

# Install tree-sitter-cli
if ! type lazygit; then
  echo "Installing tree-sitter-cli..."
  sudo npm install tree-sitter-cli -g
  echo "tree-sitter-cli installed!"
fi

# Install Oh-my-zsh
if [ ! -d $HOME/.oh-my-zsh ]; then
  echo "Installing oh-my-zsh..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  echo "oh-my-zsh installed!"
fi

# Install tmux
if ! type tmux; then
  echo "Installing tmux..."
  sudo apt install -y tmux
  git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
  echo "tmux installed!"
fi

# Create symlinks
echo "Creating sym links..."
current_directory=$(pwd)
ln -sf $current_directory/nvim $HOME/.config/nvim
ln -sf $current_directory/.zshrc $HOME/.zshrc
ln -sf $current_directory/.tmux.conf $HOME/.tmux.conf
echo "Sym links created!"

zsh
